# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import likert_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', likert_field.models.LikertField(blank=True, null=True, verbose_name='음악들이 내가 입력한 주제와 잘 부합하였다.')),
                ('q2', likert_field.models.LikertField(blank=True, null=True, verbose_name='음악들의 주제가 서로 일관성이 있었다.')),
                ('q3', likert_field.models.LikertField(blank=True, null=True, verbose_name='음악들이 나의 니즈를 잘 반영하였다.')),
                ('q4', likert_field.models.LikertField(blank=True, null=True, verbose_name='이번에 새롭에 듣게 된 음악들이 있었다.')),
                ('q5', likert_field.models.LikertField(blank=True, null=True, verbose_name='이 웹사이트를 주변 사람들에게 추천하겠다.')),
                ('user', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_input', models.CharField(max_length=200)),
                ('user_output', models.CharField(max_length=200)),
            ],
        ),
    ]
