# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import likert_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', likert_field.models.LikertField(blank=True, null=True, verbose_name='입력한 쿼리와 플레이 리스트가 유사했다.')),
                ('q2', likert_field.models.LikertField(blank=True, null=True, verbose_name='플레이 리스트의 노래들이 서로 유사했다.')),
                ('q3', likert_field.models.LikertField(blank=True, null=True, verbose_name='seven is my lucky number.')),
                ('q4', likert_field.models.LikertField(blank=True, null=True, verbose_name='dgag.')),
                ('q5', likert_field.models.LikertField(blank=True, null=True, verbose_name='이 플레이 리스트를 내 친구에게 공유하고 싶다.')),
                ('user', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
